config_file_path: configs/escnn/sinkhorn_trainable_sigma_ota.yml
data:
  batch_size: 128
  image_size:
  - 80
  - 80
  include_rotations: false
  num_workers: 4
  sampler_power: 1.0
  sampler_replacement: true
  sampler_smoothing: 0.0
  seed: 42
  shared_norm: false
  source_img_dir: data/source/galaxy_images_rgb
  source_labels: data/source/source_galaxy_labels.csv
  source_mean:
  - 0.10847612470388412
  - 0.11747581511735916
  - 0.09117262810468674
  source_std:
  - 0.2002607136964798
  - 0.21037432551383972
  - 0.18275086581707
  target_img_dir: data/target/gz2_images
  target_labels: data/target/gz2_galaxy_labels.csv
  target_mean:
  - 0.04404614865779877
  - 0.03992335870862007
  - 0.032842349261045456
  target_std:
  - 0.08452991396188736
  - 0.07349640130996704
  - 0.07248455286026001
  use_sampler: false
  val_size: 0.2
experiment_name: sinkhorn_trainable_sigma_ota
model:
  N: 8
  base_width: 24
  dropout: 0.4
  group: E2
  type: escnn
output:
  root_dir: ota_experiments/escnn
seed: 42
training:
  class_weight_beta: 0.9999
  class_weight_method: effective
  criterion: focal
  early_stopping_metric: train_loss
  early_stopping_patience: 8
  eta_1_init: 0.1
  eta_2_init: 1.0
  focal_alpha: class_weights
  focal_gamma: 2.0
  focal_reduction: mean
  lambda_da: 0.25
  lambda_entropy: 0.02
  lambda_ot: 0.5
  lr: 0.0001
  lr_scheduler: cosine
  match_epsilon: 0.05
  match_n_iter: 20
  max_norm: 10.0
  method: sinkhorn
  min_lr: 1.0e-06
  num_epochs: 200
  optimizer: adamw
  ot_epsilon: 0.05
  ot_lambda_match: 0.6
  ot_lambda_ot: 0.3
  ot_lambda_topk: 0.1
  ot_n_iter: 50
  ot_topk: 5
  sigma_decay_rate: 0.95
  sigma_final_blur: 1.0
  sigma_initial_blur: 10.0
  sigma_min_blur: 0.01
  sigma_poly_power: 2.0
  sigma_schedule_type: exponential
  sigma_step_gamma: 0.5
  sigma_step_size: 2
  sinkhorn_blur: 10.0
  sinkhorn_p: 2
  use_class_weights: true
  use_sigma_schedule: true
  use_trainable_weights: true
  warmup_epochs: 8
  weight_decay: 0.01
