config_file_path: configs/escnn/adversarial_ota.yml
data:
  batch_size: 128
  image_size:
  - 80
  - 80
  include_rotations: false
  num_workers: 4
  sampler_power: 1.0
  sampler_replacement: true
  sampler_smoothing: 0.0
  seed: 42
  shared_norm: false
  source_img_dir: data/source/galaxy_images_rgb
  source_labels: data/source/source_galaxy_labels.csv
  source_mean:
  - 0.10847612470388412
  - 0.11747581511735916
  - 0.09117262810468674
  source_std:
  - 0.2002607136964798
  - 0.21037432551383972
  - 0.18275086581707
  target_img_dir: data/target/gz2_images
  target_labels: data/target/gz2_galaxy_labels.csv
  target_mean:
  - 0.04404614865779877
  - 0.03992335870862007
  - 0.032842349261045456
  target_std:
  - 0.08452991396188736
  - 0.07349640130996704
  - 0.07248455286026001
  use_sampler: false
  val_size: 0.1
experiment_name: adversarial_ota
model:
  N: 8
  base_width: 24
  dropout: 0.4
  group: E2
  type: escnn
output:
  root_dir: ota_experiments/escnn
seed: 42
training:
  class_weight_beta: 0.9999
  class_weight_method: effective
  criterion: focal
  domain_hidden_dim: 256
  domain_projection_dim: 128
  early_stopping_metric: train_loss
  early_stopping_patience: 8
  focal_alpha: class_weights
  focal_gamma: 2.0
  focal_reduction: mean
  lambda_entropy: 0.02
  lambda_grl: 0.4
  lambda_grl_schedule:
    end: 0.4
    start: 0.0
    type: sigmoid
  lambda_ot: 0.5
  latent_dim: 96
  lr: 0.0001
  lr_scheduler: cosine
  match_epsilon: 0.05
  match_n_iter: 20
  max_norm: 10.0
  method: adversarial
  min_lr: 1.0e-06
  num_epochs: 200
  optimizer: adamw
  ot_epsilon: 0.05
  ot_lambda_match: 0.6
  ot_lambda_ot: 0.3
  ot_lambda_topk: 0.1
  ot_n_iter: 50
  ot_topk: 5
  use_class_weights: true
  use_projection: true
  warmup_epochs: 8
  weight_decay: 0.01
